"""empty message

Revision ID: 3a6cd98e2c8a
Revises: 
Create Date: 2023-06-12 23:32:38.732114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6cd98e2c8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('login', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_login'), ['login'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_password'), ['password'], unique=False)

    op.create_table('analytic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(length=100), nullable=False),
    sa.Column('server_code', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_code'], ['server.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analytic_id', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Float(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('country_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['analytic_id'], ['analytic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic')
    op.drop_table('analytic')
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_password'))
        batch_op.drop_index(batch_op.f('ix_server_login'))
        batch_op.drop_index(batch_op.f('ix_server_ip'))

    op.drop_table('server')
    # ### end Alembic commands ###
